import { useFileState } from './useFileState'
import { usePlaybackState } from './usePlaybackState'
import { isDirectPlayable } from '../utils/appControllerUtils'

export function useAppController() {
  const {
    files,
    filteredFiles,
    selectedFile,
    setSelectedFile,
    searchTerm,
    filterDecoded,
    sortKey,
    sortDir,
    isTableOpen,
    isSidebarCollapsed,
    isDarkMode,
    loadFiles,
    setSearchTerm,
    setFilterDecoded,
    handleSortChange,
    handleFileSelect,
    handleNext,
    handlePrev,
    pickDirectory,
    toggleSidebar,
    toggleTable,
    toggleTheme
  } = useFileState()

  const {
    isDecoding,
    activeSession,
    playbackRate,
    volume,
    outputFormat,
    convertFormat,
    isConverting,
    waveformRef,
    audioRef,
    nativeTime,
    nativeDuration,
    nativePlaying,
    forceNativeAudio,
    wavesurferRef,
    isWaveformReady,
    isPlaying,
    currentTime,
    duration,
    setOutputFormat,
    setConvertFormat,
    handleDecodeAndPlay,
    handleDownload,
    handleConvertAndDownload,
    handleRateChange,
    handleSeek,
    handleSkip,
    handleVolumeChange,
    playPause,
    streamingPeaks,
    streamingDuration,
    isChunkedStreaming
  } = usePlaybackState({
    selectedFile,
    setSelectedFile,
    loadFiles
  })

  return {
    files,
    filteredFiles,
    selectedFile,
    isDecoding,
    activeSession,
    playbackRate,
    volume,
    outputFormat,
    convertFormat,
    searchTerm,
    filterDecoded,
    sortKey,
    sortDir,
    isConverting,
    isTableOpen,
    isSidebarCollapsed,
    isDarkMode,
    waveformRef,
    audioRef,
    nativeTime,
    nativeDuration,
    nativePlaying,
    forceNativeAudio,
    wavesurferRef,
    isWaveformReady,
    isPlaying,
    currentTime,
    duration,
    setSearchTerm,
    setFilterDecoded,
    setOutputFormat,
    setConvertFormat,
    handleSortChange,
    handleFileSelect,
    handleDecodeAndPlay,
    handleDownload,
    handleConvertAndDownload,
    handleNext,
    handlePrev,
    handleRateChange,
    handleSeek,
    handleSkip,
    handleVolumeChange,
    pickDirectory,
    playPause,
    toggleSidebar,
    toggleTable,
    toggleTheme,
    isDirectPlayable,
    streamingPeaks,
    streamingDuration,
    isChunkedStreaming
  }
}
